name: Docs

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org'
      - name: init
        run: |
          npm i -g pnpm
          pnpm install
      - name: generate storybook
        run: pnpm build-storybook
      - name: Create new commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.email "github-actions@xpadev.net"
          git config user.name "github-actions"
          git fetch --all
          git switch storybook
          rm -rf ./docs
          mv -f ./storybook-static ./docs
          touch ./docs/.nojekyll
          git add .
          git commit -m "docs" -n
          git push -f origin storybook
